---
- name: Create namespace for Rancher Control Plane
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    api_version: v1
    kind: Namespace
    name: cattle-system
  vars:
    cluster: "{{ groups['rke_' + inventory_hostname] }}"

- name: Create namespace for cert-manager
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    api_version: v1
    kind: Namespace
    name: cert-manager
  vars:
    cluster: "{{ groups['rke_' + inventory_hostname] }}"
  when:
  - certmanager_enabled

- name: Add Rancher Repo to Helm
  command: "{{ helm_binary }} repo add --kubeconfig {{ rke_cluster_kube_config }} {{ rancher_repo }} {{ rancher_repo_url }}"
  changed_when: false

- name: Add Jetstack Cert-Manager Repo to Helm
  command: "{{ helm_binary }} repo add --kubeconfig {{ rke_cluster_kube_config }} {{ jetstack_repo }} {{ jetstack_repo_url }}"
  changed_when: false
  when:
  - certmanager_enabled

- name: Update Helm Repo
  command: "{{ helm_binary }} repo update --kubeconfig {{ rke_cluster_kube_config }}"
  changed_when: false

- name: Install CRD's for CertManager
  command: "{{ kubectl_binary }} --kubeconfig {{ rke_cluster_kube_config }} apply --validate=false -f {{ certmanager_crd_url }}"
  changed_when: false
  ignore_errors: yes
  when:
  - certmanager_enabled

- name: Install Cert-Manager
  command: "{{ helm_binary }} upgrade --install --kubeconfig {{ rke_cluster_kube_config }} --namespace cert-manager --version {{ rancher_certmanager_version }} cert-manager {{ jetstack_repo }}/cert-manager"
  changed_when: false
  when:
  - certmanager_enabled

- name: Wait for certmanager to be ready
  command: "{{ kubectl_binary }} -n cert-manager --kubeconfig {{ rke_cluster_kube_config }} rollout status deploy/cert-manager"
  changed_when: false
  when:
  - certmanager_enabled

- name: Wait for certmanager cainjector to be ready
  command: "{{ kubectl_binary }} -n cert-manager --kubeconfig {{ rke_cluster_kube_config }} rollout status deploy/cert-manager-cainjector"
  changed_when: false
  when:
  - certmanager_enabled

- name: Wait for certmanager webhook to be ready
  command: "{{ kubectl_binary }} -n cert-manager --kubeconfig {{ rke_cluster_kube_config }} rollout status deploy/cert-manager-webhook"
  changed_when: false
  when:
  - certmanager_enabled

- name: Install Rancher with Let's Encrypt
  command: "{{ helm_binary }} upgrade --install --kubeconfig {{ rke_cluster_kube_config }} --namespace cattle-system --set hostname={{ rancher_hostname }} --set ingress.tls.source=letsEncrypt --set letsEncrypt.email={{ rancher_letsencrypt_email }} --version {{ rancher_version }} rancher {{ rancher_repo }}/rancher"
  changed_when: false
  when:
  - certmanager_enabled

- name: Install Rancher without Let's Encrypt
  command: "{{ helm_binary }} upgrade --install --kubeconfig {{ rke_cluster_kube_config }} --namespace cattle-system --set hostname={{ rancher_hostname }} --set ingress.tls.source=secret --version {{ rancher_version }} rancher {{ rancher_repo }}/rancher"
  changed_when: false
  when:
  - not certmanager_enabled

- name: Create tls secret when not using Let's Encrypt
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: tls-rancher-ingress
        namespace: cattle-system
      data:
        tls.crt: "{{ rke_rancher_tls_crt }}"
        tls.key: "{{ rke_rancher_tls_key }}"
      type: kubernetes.io/tls
  when:
  - not certmanager_enabled

- name: Create tls cacerts secret when not using Let's Encrypt and using self-signed Rancher TLS cert
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: tls-ca
        namespace: cattle-system
      data:
        cacerts.pem: "{{ rke_rancher_tls_cacerts }}"
  when:
  - not certmanager_enabled
  - rke_rancher_tls_self_signed

- name: Wait for Rancher Deployment to be ready
  command: "{{ kubectl_binary }} -n cattle-system --kubeconfig {{ rke_cluster_kube_config }} rollout status deploy/rancher"
  changed_when: false

- name: Wait for Rancher to be ready
  command: "curl -k --silent https://{{ rancher_hostname }}/ping"
  args:
    warn: no
  register: rancher_ready
  until: rancher_ready.stdout.find("pong") != -1
  retries: 24
  delay: 5
  changed_when: false
  check_mode: no
