---
- hosts: rke_nginx_loadbalancer
  vars:
    nodes: "{{ groups['rke_cluster_rancher'] }}"
    http_servers: >
      {% for node in nodes %}
      {{ node }}:
        address: {{ hostvars[node]['ansible_' + rke_network_interface]['ipv4']['address'] }}
        port: 80
        health_check: max_fails=3 fail_timeout=5s
      {% endfor %}
    https_servers: >
      {% for node in nodes %}
      {{ node }}:
        address: {{ hostvars[node]['ansible_' + rke_network_interface]['ipv4']['address'] }}
        port: 443
        health_check: max_fails=3 fail_timeout=5s
      {% endfor %}
  collections:
    - nginxinc.nginx_core

  roles:
    - role: nginx
    - role: nginx_config
      vars:
        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          conf_file_name: nginx.conf
          conf_file_location: /etc/nginx/
          user: nginx
          worker_processes: 4
          worker_rlimit_nofile: 40000
          worker_connections: 8192
          http_enable: false
          stream_enable: true
        nginx_config_stream_template_enable: true
        nginx_config_stream_template:
          default:
             template_file: stream/default.conf.j2
             conf_file_name: default.conf
             conf_file_location: /etc/nginx/conf.d/stream/
             network_streams:
               rancher_servers_http:
                 listen:
                   listen_localhost:
                     ip: 0.0.0.0
                     port: 80
                 proxy_pass: rancher_servers_http
                 proxy_timeout: 60s
                 proxy_connect_timeout: 60s
                 proxy_protocol: false
                 health_check_plus: false
               rancher_servers_https:
                 listen:
                   listen_localhost:
                     ip: 0.0.0.0
                     port: 443
                 proxy_pass: rancher_servers_https
                 proxy_timeout: 60s
                 proxy_connect_timeout: 60s
                 proxy_protocol: false
                 health_check_plus: false
             upstreams:
               rancher_servers_http:
                 name: rancher_servers_http
                 lb_method: least_conn
                 zone_name: rancher_servers_http
                 zone_size: 128k
                 servers: "{{ http_servers | from_yaml }}"
               rancher_servers_https:
                 name: rancher_servers_https
                 lb_method: least_conn
                 zone_name: rancher_servers_https
                 zone_size: 128k
                 servers: "{{ https_servers | from_yaml }}"