---

- name: Create or get Cluster
  delegate_to: localhost
  import_tasks: cluster.yml

- name: Nodes
  delegate_to: localhost
  import_tasks: nodes.yml

- name: Configure keepalived
  include_role:
    name: keepalived
    public: yes
  vars:
    keepalived_cluster_group_inventory_name: "{{ custom_k8s_cluster_group_inventory_name }}"
